/** @type {import('next-sitemap').IConfig} */
// NOTE: The primary sitemap is now generated by Next.js App Router via
// src/app/sitemap.ts (served at /sitemap.xml without a build step).
// This config is kept as a reference / backup only. If you re-enable
// next-sitemap by adding "postbuild": "next-sitemap" to package.json,
// make sure SITE_URL is set in your Vercel environment variables.
module.exports = {
  siteUrl: process.env.SITE_URL || "https://webmind-ai.vercel.app",
  generateRobotsTxt: false, // robots.ts in App Router handles this
  alternateRefs: [
    { href: "https://webmind-ai.vercel.app",      hreflang: "en" },
    { href: "https://webmind-ai.vercel.app/tr",   hreflang: "tr" },
    { href: "https://webmind-ai.vercel.app",      hreflang: "x-default" },
  ],
  exclude: ["/server-sitemap.xml"],
  transform: async (config, path) => {
    const priority =
      path === "/" || path === "/tr" ? 1.0
      : path.includes("/webllm") || path.includes("/transformers") ? 0.9
      : 0.7;
    return {
      loc: path,
      changefreq: "weekly",
      priority,
      lastmod: new Date().toISOString(),
    };
  },
};
