// Transformers.js görev ve model tanımları — Hugging Face tarafından desteklenen modeller

export type TaskCategory = "nlp" | "vision" | "audio" | "multimodal";
export type InputType = "text" | "image" | "audio" | "text+image";

export interface TransformersModel {
  id: string;           // Hugging Face model ID
  name: string;         // Kullanıcıya gösterilen isim
  task: string;         // Transformers.js pipeline task adı
  taskLabel: { en: string; tr: string };
  company: string;
  companyLogo: string;
  sizeMB: number;
  minVramMB: number;    // 0 ise CPU (WebAssembly) ile çalışabilir
  category: TaskCategory;
  inputType: InputType;
  license: string;
  description: { en: string; tr: string };
  advantages: { en: string[]; tr: string[] };
  useCases: { en: string[]; tr: string[] };
  badge?: "popular" | "new" | "recommended";
  resultType: "labels" | "text" | "boxes" | "embeddings" | "audio";
}

export const transformersModels: TransformersModel[] = [
  {
    id: "Xenova/distilbert-base-uncased-finetuned-sst-2-english",
    name: "DistilBERT Sentiment",
    task: "sentiment-analysis",
    taskLabel: { en: "Sentiment Analysis", tr: "Duygu Analizi" },
    company: "Hugging Face",
    companyLogo: "🤗",
    sizeMB: 67,
    minVramMB: 0,
    category: "nlp",
    inputType: "text",
    license: "Apache 2.0",
    badge: "popular",
    description: {
      en: "Analyzes the emotional tone of text — positive, negative, or neutral. Fast and lightweight.",
      tr: "Metnin duygusal tonunu analiz eder — pozitif, negatif veya nötr. Hızlı ve hafif.",
    },
    advantages: { en: ["Tiny 67MB model", "CPU-friendly", "Instant results"], tr: ["67MB küçük model", "CPU dostu", "Anlık sonuçlar"] },
    useCases: { en: ["Customer feedback", "Social media monitoring", "Review analysis"], tr: ["Müşteri geri bildirimi", "Sosyal medya izleme", "Yorum analizi"] },
    resultType: "labels",
  },
  {
    id: "Xenova/bert-base-NER",
    name: "BERT NER",
    task: "token-classification",
    taskLabel: { en: "Named Entity Recognition", tr: "Adlandırılmış Varlık Tanıma" },
    company: "Hugging Face",
    companyLogo: "🤗",
    sizeMB: 420,
    minVramMB: 0,
    category: "nlp",
    inputType: "text",
    license: "MIT",
    description: {
      en: "Identifies and classifies named entities in text — people, organizations, locations, dates.",
      tr: "Metindeki adlandırılmış varlıkları tanımlar — kişiler, organizasyonlar, konumlar, tarihler.",
    },
    advantages: { en: ["Detailed entity extraction", "Multilingual variants available", "CPU compatible"], tr: ["Ayrıntılı varlık çıkarma", "Çok dilli varyantlar", "CPU uyumlu"] },
    useCases: { en: ["Document parsing", "Information extraction", "Knowledge graphs"], tr: ["Belge ayrıştırma", "Bilgi çıkarma", "Bilgi grafikleri"] },
    resultType: "labels",
  },
  {
    id: "Xenova/nllb-200-distilled-600M",
    name: "NLLB-200 Translation",
    task: "translation",
    taskLabel: { en: "Translation", tr: "Çeviri" },
    company: "Meta",
    companyLogo: "🦙",
    sizeMB: 1200,
    minVramMB: 0,
    category: "nlp",
    inputType: "text",
    license: "CC-BY-NC",
    badge: "recommended",
    description: {
      en: "Meta's No Language Left Behind model — translates between 200 languages including Turkish, Kurdish, and many low-resource languages.",
      tr: "Meta'nın 'Hiçbir Dil Geride Kalmasın' modeli — Türkçe, Kürtçe ve birçok az kaynaklı dil dahil 200 dil arasında çeviri yapar.",
    },
    advantages: { en: ["200 language support", "Rare language coverage", "No API key needed"], tr: ["200 dil desteği", "Nadir diller dahil", "API anahtarı gerekmez"] },
    useCases: { en: ["Document translation", "Multilingual apps", "Language learning"], tr: ["Belge çevirisi", "Çok dilli uygulamalar", "Dil öğrenimi"] },
    resultType: "text",
  },
  {
    id: "Xenova/distilbart-cnn-6-6",
    name: "DistilBART Summarization",
    task: "summarization",
    taskLabel: { en: "Text Summarization", tr: "Metin Özetleme" },
    company: "Hugging Face",
    companyLogo: "🤗",
    sizeMB: 700,
    minVramMB: 0,
    category: "nlp",
    inputType: "text",
    license: "Apache 2.0",
    description: {
      en: "Condenses long documents into concise summaries. Based on BART architecture distilled for speed.",
      tr: "Uzun belgeleri özlü özetlere sıkıştırır. Hız için damıtılmış BART mimarisine dayanır.",
    },
    advantages: { en: ["Fast summarization", "CPU compatible", "Good quality summaries"], tr: ["Hızlı özetleme", "CPU uyumlu", "Kaliteli özetler"] },
    useCases: { en: ["News summarization", "Research papers", "Meeting notes"], tr: ["Haber özetleme", "Araştırma makaleleri", "Toplantı notları"] },
    resultType: "text",
  },
  {
    id: "Xenova/distilbert-base-cased-distilled-squad",
    name: "DistilBERT QA",
    task: "question-answering",
    taskLabel: { en: "Question Answering", tr: "Soru Cevaplama" },
    company: "Hugging Face",
    companyLogo: "🤗",
    sizeMB: 260,
    minVramMB: 0,
    category: "nlp",
    inputType: "text",
    license: "Apache 2.0",
    description: {
      en: "Extracts answers from a given context passage. Fast and accurate for reading comprehension tasks.",
      tr: "Verilen bir bağlam pasajından cevapları çıkarır. Okuma anlama görevleri için hızlı ve doğru.",
    },
    advantages: { en: ["Extractive QA", "Very fast", "No generation needed"], tr: ["Çıkarıcı soru-cevap", "Çok hızlı", "Üretim gerekmez"] },
    useCases: { en: ["Document QA", "Support bots", "Knowledge base search"], tr: ["Belge soru-cevap", "Destek botları", "Bilgi tabanı arama"] },
    resultType: "text",
  },
  {
    id: "Xenova/bart-large-mnli",
    name: "BART Zero-Shot Classification",
    task: "zero-shot-classification",
    taskLabel: { en: "Zero-Shot Classification", tr: "Sıfır-Atış Sınıflandırma" },
    company: "Meta",
    companyLogo: "🦙",
    sizeMB: 1600,
    minVramMB: 1024,
    category: "nlp",
    inputType: "text",
    license: "MIT",
    description: {
      en: "Classifies text into categories without any training examples. Define your own labels at runtime.",
      tr: "Herhangi bir eğitim örneği olmadan metni kategorilere ayırır. Çalışma zamanında kendi etiketlerinizi tanımlayın.",
    },
    advantages: { en: ["No training needed", "Custom labels", "Flexible classification"], tr: ["Eğitim gerekmez", "Özel etiketler", "Esnek sınıflandırma"] },
    useCases: { en: ["Content categorization", "Intent detection", "Topic classification"], tr: ["İçerik kategorisi", "Niyet tespiti", "Konu sınıflandırma"] },
    resultType: "labels",
  },
  {
    id: "Xenova/vit-base-patch16-224",
    name: "ViT Image Classification",
    task: "image-classification",
    taskLabel: { en: "Image Classification", tr: "Görüntü Sınıflandırma" },
    company: "Google",
    companyLogo: "🔷",
    sizeMB: 330,
    minVramMB: 512,
    category: "vision",
    inputType: "image",
    license: "Apache 2.0",
    badge: "popular",
    description: {
      en: "Classifies images into 1000 ImageNet categories. Vision Transformer architecture for accurate recognition.",
      tr: "Görüntüleri 1000 ImageNet kategorisine sınıflandırır. Doğru tanıma için Vision Transformer mimarisi.",
    },
    advantages: { en: ["1000 categories", "High accuracy", "Vision Transformer architecture"], tr: ["1000 kategori", "Yüksek doğruluk", "Vision Transformer mimarisi"] },
    useCases: { en: ["Photo categorization", "Content moderation", "Visual search"], tr: ["Fotoğraf kategorisi", "İçerik moderasyonu", "Görsel arama"] },
    resultType: "labels",
  },
  {
    id: "Xenova/detr-resnet-50",
    name: "DETR Object Detection",
    task: "object-detection",
    taskLabel: { en: "Object Detection", tr: "Nesne Tespiti" },
    company: "Meta",
    companyLogo: "🦙",
    sizeMB: 160,
    minVramMB: 512,
    category: "vision",
    inputType: "image",
    license: "Apache 2.0",
    badge: "recommended",
    description: {
      en: "Detects and localizes multiple objects in images using the DETR transformer architecture.",
      tr: "DETR transformer mimarisini kullanarak görüntülerdeki birden fazla nesneyi tespit eder ve konumlandırır.",
    },
    advantages: { en: ["Multi-object detection", "Bounding boxes", "End-to-end transformer"], tr: ["Çoklu nesne tespiti", "Sınırlayıcı kutular", "Uçtan uca transformer"] },
    useCases: { en: ["Autonomous systems", "Security cameras", "Inventory management"], tr: ["Otonom sistemler", "Güvenlik kameraları", "Stok yönetimi"] },
    resultType: "boxes",
  },
  {
    id: "Xenova/depth-anything-small-hf",
    name: "Depth Anything",
    task: "depth-estimation",
    taskLabel: { en: "Depth Estimation", tr: "Derinlik Tahmini" },
    company: "ByteDance",
    companyLogo: "📱",
    sizeMB: 100,
    minVramMB: 512,
    category: "vision",
    inputType: "image",
    license: "Apache 2.0",
    badge: "new",
    description: {
      en: "Estimates the depth map of any image. Creates 3D-like visualizations from regular 2D photos.",
      tr: "Herhangi bir görüntünün derinlik haritasını tahmin eder. Normal 2D fotoğraflardan 3D görselleştirmeler oluşturur.",
    },
    advantages: { en: ["Any image input", "Fast monocular depth", "Small model size"], tr: ["Herhangi bir görüntü", "Hızlı monoküler derinlik", "Küçük model boyutu"] },
    useCases: { en: ["3D reconstruction", "AR apps", "Photo editing"], tr: ["3B yeniden yapılandırma", "AR uygulamaları", "Fotoğraf düzenleme"] },
    resultType: "labels",
  },
  {
    id: "Xenova/whisper-tiny",
    name: "Whisper Tiny ASR",
    task: "automatic-speech-recognition",
    taskLabel: { en: "Speech Recognition", tr: "Konuşma Tanıma" },
    company: "OpenAI",
    companyLogo: "🤖",
    sizeMB: 150,
    minVramMB: 0,
    category: "audio",
    inputType: "audio",
    license: "MIT",
    badge: "popular",
    description: {
      en: "OpenAI's Whisper model for speech-to-text. Transcribes audio in 99 languages directly in the browser.",
      tr: "OpenAI'nın konuşmadan metne Whisper modeli. 99 dilde sesi doğrudan tarayıcıda metne çevirir.",
    },
    advantages: { en: ["99 language support", "MIT license", "CPU compatible", "No API needed"], tr: ["99 dil desteği", "MIT lisansı", "CPU uyumlu", "API gerekmez"] },
    useCases: { en: ["Meeting transcription", "Subtitle generation", "Voice commands"], tr: ["Toplantı transkripsiyonu", "Altyazı üretimi", "Sesli komutlar"] },
    resultType: "text",
  },
  {
    id: "Xenova/clip-vit-base-patch32",
    name: "CLIP Vision-Language",
    task: "zero-shot-image-classification",
    taskLabel: { en: "Image-Text Matching", tr: "Görüntü-Metin Eşleştirme" },
    company: "OpenAI",
    companyLogo: "🤖",
    sizeMB: 600,
    minVramMB: 512,
    category: "multimodal",
    inputType: "text+image",
    license: "MIT",
    description: {
      en: "OpenAI's CLIP model that understands both images and text. Classify images with custom text labels.",
      tr: "OpenAI'nın hem görüntüleri hem de metni anlayan CLIP modeli. Özel metin etiketleriyle görüntüleri sınıflandırın.",
    },
    advantages: { en: ["Multimodal understanding", "Custom labels", "Zero-shot capability"], tr: ["Çok modlu anlama", "Özel etiketler", "Sıfır-atış yeteneği"] },
    useCases: { en: ["Visual search", "Image tagging", "Content filtering"], tr: ["Görsel arama", "Görüntü etiketleme", "İçerik filtreleme"] },
    resultType: "labels",
  },
  {
    id: "Xenova/LaMini-Flan-T5-248M",
    name: "LaMini Text Generation",
    task: "text2text-generation",
    taskLabel: { en: "Text Generation", tr: "Metin Üretimi" },
    company: "Hugging Face",
    companyLogo: "🤗",
    sizeMB: 940,
    minVramMB: 512,
    category: "nlp",
    inputType: "text",
    license: "CC-BY-NC",
    description: {
      en: "Instruction-following text generation model. Great for rewriting, paraphrasing, and completing text.",
      tr: "Talimat takip eden metin üretim modeli. Yeniden yazma, başka deyişle ifade ve metin tamamlama için harika.",
    },
    advantages: { en: ["Instruction tuned", "Fast generation", "Low resource needs"], tr: ["Talimat ayarlı", "Hızlı üretim", "Düşük kaynak ihtiyacı"] },
    useCases: { en: ["Text rewriting", "Paraphrasing", "Email drafting"], tr: ["Metin yeniden yazma", "Başka deyişle ifade", "E-posta taslağı"] },
    resultType: "text",
  },
];
