import { MetadataRoute } from "next";

const BASE_URL = "https://webmind-ai.vercel.app";

// Served at /robots.txt — generated by Next.js App Router at build time.
// Explicitly allows major AI crawlers so WebMind appears in AI Overviews,
// ChatGPT search, Perplexity, and Bing Copilot.
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/_next/"],
      },
      // AI search crawlers — explicit allow signals GEO readiness
      { userAgent: "GPTBot", allow: "/" },
      { userAgent: "OAI-SearchBot", allow: "/" },
      { userAgent: "ClaudeBot", allow: "/" },
      { userAgent: "anthropic-ai", allow: "/" },
      { userAgent: "PerplexityBot", allow: "/" },
      { userAgent: "Google-Extended", allow: "/" },
      { userAgent: "CCBot", allow: "/" },
    ],
    sitemap: `${BASE_URL}/sitemap.xml`,
  };
}
